language: "node_js"
node_js:
  - "node"
  - "lts/*"
before_install: npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: npm run report-coverage
